export const SEARCH_ROUTES = [
  { href: "/", label: "Anasayfa", icon: "🏠", keywords: ["home"] },
  { href: "/hizmetler", label: "Hizmetler", icon: "🧰", keywords: ["servis"] },
  { href: "/hakkimizda", label: "Hakkımızda", icon: "👥", keywords: ["biz", "firma"] },
  { href: "/blog", label: "Blog", icon: "📝", keywords: ["yazılar"] },
  { href: "/iletisim", label: "İletişim", icon: "📞", keywords: ["telefon", "mail"] },
  { href: "/nasil-calisiyoruz", label: "Nasıl Çalışıyoruz", icon: "🧭", keywords: ["süreç"] },
  { href: "/bolgesel-kiralama", label: "Bölgesel Kiralama", icon: "🗺️", keywords: ["lojistik"] },
  { href: "/sss", label: "SSS", icon: "💡", keywords: ["sık sorulan"] },
  { href: "/podyum-kiralama", label: "Podyum Kiralama", icon: "👑", keywords: ["sahne"] },
  { href: "/led-ekran-kiralama", label: "LED Ekran Kiralama", icon: "🖥️", keywords: ["video wall"] },
  { href: "/ses-isik-sistemleri", label: "Ses & Işık Sistemleri", icon: "🎭", keywords: ["ışık", "ses"] },
  { href: "/sahne-kiralama", label: "Sahne Kiralama", icon: "🎪", keywords: ["platform"] },
  { href: "/kurumsal-organizasyon", label: "Kurumsal Organizasyon", icon: "🏢", keywords: ["etkinlik"] },
  { href: "/truss-kiralama", label: "Truss Kiralama", icon: "🧩", keywords: ["konstrüksiyon"] },
  { href: "/cadir-kiralama", label: "Çadır Kiralama", icon: "⛺", keywords: ["çadır"] },
  { href: "/masa-sandalye-kiralama", label: "Masa Sandalye Kiralama", icon: "🪑", keywords: ["oturma"] },
];
