export const SEARCH_ROUTE_GROUPS = {
  tr: [
    { href: "/", label: "Anasayfa", icon: "\u{1F3E0}", keywords: ["home"] },
    { href: "/hizmetler", label: "Hizmetler", icon: "\u{1F9F0}", keywords: ["servis"] },
    { href: "/hakkimizda", label: "Hakkımızda", icon: "\u{1F465}", keywords: ["biz", "firma"] },
    { href: "/blog", label: "Blog", icon: "\u{1F4DD}", keywords: ["yazilar"] },
    { href: "/iletisim", label: "İletişim", icon: "\u{260E}", keywords: ["telefon", "mail"] },
    { href: "/nasil-calisiyoruz", label: "Nasıl Çalışıyoruz", icon: "\u{1F9ED}", keywords: ["surec"] },
    { href: "/bolgesel-kiralama", label: "Bölgesel Kiralama", icon: "\u{1F5FA}", keywords: ["lojistik"] },
    { href: "/sss", label: "SSS", icon: "\u{1F4A1}", keywords: ["sik sorulan"] },
    { href: "/sozluk", label: "Sözlük", icon: "\u{1F4D6}", keywords: ["terim", "sozluk", "nedir", "pixel pitch", "line array", "truss nedir", "teknik terimler"] },
    { href: "/podyum-kiralama", label: "Podyum Kiralama", icon: "\u{1F451}", keywords: ["sahne"] },
    { href: "/led-ekran-kiralama", label: "LED Ekran Kiralama", icon: "\u{1F5A5}", keywords: ["video wall"] },
    { href: "/ses-isik-sistemleri", label: "Ses ve Işık Sistemleri", icon: "\u{1F3AD}", keywords: ["isik", "ses"] },
    { href: "/sahne-kiralama", label: "Sahne Kiralama", icon: "\u{1F3AA}", keywords: ["platform"] },
    { href: "/kurumsal-organizasyon", label: "Kurumsal Organizasyon", icon: "\u{1F3E2}", keywords: ["etkinlik"] },
    { href: "/turkiyede-etkinlik-cozum-ortagi", label: "Türkiye'de Etkinlik Çözüm Ortağı", icon: "\u{1F310}", keywords: ["international", "uluslararasi", "turkiye etkinlik", "Türkiye etkinlik çözüm ortağı", "yabancı firmalar için etkinlik prodüksiyonu", "uluslararası etkinlik prodüksiyonu", "Avrupa'dan gelen firmalar için etkinlik", "e-spor etkinlik prodüksiyonu", "sahne LED ses ışık Türkiye"] },
    { href: "/truss-kiralama", label: "Truss Kiralama", icon: "\u{1F9E9}", keywords: ["konstruksiyon"] },
    { href: "/cadir-kiralama", label: "Çadır Kiralama", icon: "\u26FA", keywords: ["cadir"] },
    { href: "/masa-sandalye-kiralama", label: "Masa Sandalye Kiralama", icon: "\u{1FA91}", keywords: ["oturma"] },
    { href: "/sisme-oyun-parki-kiralama", label: "Şişme Oyun Parkı Kiralama", icon: "\u{1F3AA}", keywords: ["şişme oyun alanı", "şişme oyuncak", "oyun parkuru", "engelli parkur", "takım oyunları", "survivor parkuru"] },
    { href: "/etkinlik-personel-temini", label: "Etkinlik Personel Temini", icon: "\u{1F465}", keywords: ["personel", "guvenlik", "temizlik", "hostes", "ikram"] },
  ],
  en: [
    { href: "/en", label: "Home", icon: "\u{1F3E0}", keywords: ["home"] },
    { href: "/en/about", label: "About Us", icon: "\u{1F465}", keywords: ["company", "about"] },
    { href: "/en/services", label: "Services", icon: "\u{1F9F0}", keywords: ["service"] },
    { href: "/en/blog", label: "Blog", icon: "\u{1F4DD}", keywords: ["articles"] },
    { href: "/en/contact", label: "Contact", icon: "\u{260E}", keywords: ["phone", "email"] },
    { href: "/en/how-we-work", label: "How We Work", icon: "\u{1F9ED}", keywords: ["process"] },
    { href: "/en/regional-rental", label: "Regional Rental", icon: "\u{1F5FA}", keywords: ["logistics"] },
    { href: "/en/faq", label: "FAQ", icon: "\u{1F4A1}", keywords: ["questions"] },
    { href: "/en/podium-rental", label: "Podium Rental", icon: "\u{1F451}", keywords: ["stage"] },
    { href: "/en/led-screen-rental", label: "LED Screen Rental", icon: "\u{1F5A5}", keywords: ["video wall", "curved LED", "circular LED", "P1.9 LED", "flexible LED screen"] },
    { href: "/en/sound-light-rental", label: "Sound and Light Systems", icon: "\u{1F3AD}", keywords: ["sound", "light"] },
    { href: "/en/stage-rental", label: "Stage Rental", icon: "\u{1F3AA}", keywords: ["platform"] },
    { href: "/en/corporate-events", label: "Corporate Events", icon: "\u{1F3E2}", keywords: ["event"] },
    { href: "/en/hangar-event-venue-istanbul", label: "Hangar Event Venue Istanbul", icon: "\u{1F3DB}", keywords: ["venue", "event space", "hangar", "Istanbul venue", "corporate venue"] },
    { href: "/en/event-production-company-turkey", label: "Event Production Partner in Turkey", icon: "\u{1F310}", keywords: ["international", "turkey", "agency", "event production Turkey", "event production partner Turkey", "event partner Turkey", "technical production partner Turkey", "international event production Turkey", "European event agency Turkey", "stage LED sound lighting Turkey", "esports event production Turkey"] },
    { href: "/en/truss-rental", label: "Truss Rental", icon: "\u{1F9E9}", keywords: ["construction"] },
    { href: "/en/tent-rental", label: "Tent Rental", icon: "\u26FA", keywords: ["tent"] },
    { href: "/en/table-chair-rental", label: "Table and Chair Rental", icon: "\u{1FA91}", keywords: ["seating"] },
  ],
  ar: [
    { href: "/ar", label: "Arabic Home", icon: "\u{1F3E0}", keywords: ["arabic", "home"] },
    { href: "/ar/about", label: "Arabic About", icon: "\u{1F465}", keywords: ["arabic", "about"] },
    { href: "/ar/services", label: "Arabic Services", icon: "\u{1F9F0}", keywords: ["arabic", "services"] },
    { href: "/ar/event-production-company-turkey", label: "شريك إنتاج فعاليات في تركيا", icon: "\u{1F310}", keywords: ["arabic", "event production turkey", "international events turkey", "شريك فعاليات تركيا", "إنتاج فعاليات في تركيا"] },
    { href: "/ar/projects", label: "Arabic Projects", icon: "\u{1F4BC}", keywords: ["arabic", "projects"] },
    { href: "/ar/contact", label: "Arabic Contact", icon: "\u{260E}", keywords: ["arabic", "contact"] },
  ],
  ru: [
    { href: "/ru", label: "Русская главная", icon: "\u{1F3E0}", keywords: ["russian", "home", "главная"] },
    { href: "/ru/about", label: "О нас", icon: "\u{1F465}", keywords: ["russian", "about", "компания"] },
    { href: "/ru/services", label: "Услуги", icon: "\u{1F9F0}", keywords: ["russian", "services", "услуги"] },
    { href: "/ru/event-production-company-turkey", label: "Партнер по event production в Турции", icon: "\u{1F310}", keywords: ["russian", "event production turkey", "technical production turkey", "international events turkey", "европейское event agency turkey"] },
    { href: "/ru/stage-rental", label: "Аренда сцен", icon: "\u{1F3AA}", keywords: ["russian", "stage", "сцена"] },
    { href: "/ru/led-screen-rental", label: "Аренда LED-экранов", icon: "\u{1F5A5}", keywords: ["russian", "led", "экран"] },
    { href: "/ru/sound-light-rental", label: "Аренда звука и света", icon: "\u{1F3AD}", keywords: ["russian", "sound", "light", "звук", "свет"] },
    { href: "/ru/tent-rental", label: "Аренда шатров", icon: "\u26FA", keywords: ["russian", "tent", "шатер"] },
    { href: "/ru/corporate-events", label: "Корпоративные события", icon: "\u{1F3E2}", keywords: ["russian", "corporate", "корпоратив"] },
    { href: "/ru/projects", label: "Проекты", icon: "\u{1F4BC}", keywords: ["russian", "projects", "проекты"] },
    { href: "/ru/contact", label: "Контакты", icon: "\u{260E}", keywords: ["russian", "contact", "контакты"] },
  ],
  zh: [
    { href: "/zh", label: "中文首页", icon: "\u{1F3E0}", keywords: ["chinese", "home", "首页"] },
    { href: "/zh/about", label: "关于我们", icon: "\u{1F465}", keywords: ["chinese", "about", "公司"] },
    { href: "/zh/services", label: "服务项目", icon: "\u{1F9F0}", keywords: ["chinese", "services", "服务"] },
    { href: "/zh/stage-rental", label: "舞台租赁", icon: "\u{1F3AA}", keywords: ["chinese", "stage", "舞台", "舞台搭建", "土耳其舞台租赁"] },
    { href: "/zh/led-screen-rental", label: "LED屏幕租赁", icon: "\u{1F5A5}", keywords: ["chinese", "led", "屏幕", "大屏", "视频墙"] },
    { href: "/zh/sound-light-rental", label: "音响灯光租赁", icon: "\u{1F3AD}", keywords: ["chinese", "sound", "light", "音响", "灯光"] },
    { href: "/zh/tent-rental", label: "篷房租赁", icon: "⛺", keywords: ["chinese", "tent", "篷房", "帐篷"] },
    { href: "/zh/corporate-events", label: "企业活动制作", icon: "\u{1F3E2}", keywords: ["chinese", "corporate", "企业活动", "会议", "展览"] },
    { href: "/zh/projects", label: "项目案例", icon: "\u{1F4BC}", keywords: ["chinese", "projects", "案例"] },
    { href: "/zh/contact", label: "联系我们", icon: "\u{260E}", keywords: ["chinese", "contact", "联系"] },
  ],
  de: [
    { href: "/de", label: "Startseite", icon: "\u{1F3E0}", keywords: ["german", "deutsch", "home", "startseite"] },
    { href: "/de/ueber-uns", label: "Über uns", icon: "\u{1F465}", keywords: ["german", "about", "unternehmen", "firma"] },
    { href: "/de/leistungen", label: "Leistungen", icon: "\u{1F9F0}", keywords: ["german", "services", "leistungen", "veranstaltungstechnik"] },
    { href: "/de/buehne-mieten", label: "Bühne mieten", icon: "\u{1F3AA}", keywords: ["german", "stage", "bühne", "buehne", "podest", "bühnenbau"] },
    { href: "/de/led-wand-mieten", label: "LED-Wand mieten", icon: "\u{1F5A5}", keywords: ["german", "led", "led wand", "videowall", "bildschirm"] },
    { href: "/de/ton-und-lichttechnik", label: "Ton- und Lichttechnik", icon: "\u{1F3AD}", keywords: ["german", "sound", "light", "ton", "licht", "beschallung", "traversen"] },
    { href: "/de/zelt-mieten", label: "Zelt mieten", icon: "⛺", keywords: ["german", "tent", "zelt", "eventzelt", "pagodenzelt"] },
    { href: "/de/firmenevents", label: "Firmenevents", icon: "\u{1F3E2}", keywords: ["german", "corporate", "firmenevent", "firmenveranstaltung", "tagung", "kongress"] },
    { href: "/de/projekte", label: "Projekte", icon: "\u{1F4BC}", keywords: ["german", "projects", "projekte", "referenzprojekte"] },
    { href: "/de/referenzen", label: "Referenzen", icon: "\u{1F3AC}", keywords: ["german", "our work", "referenzen", "videos"] },
    { href: "/de/eventproduktion-tuerkei", label: "Eventproduktion Türkei", icon: "\u{1F310}", keywords: ["german", "technikpartner tuerkei", "eventagentur tuerkei", "eventproduktion tuerkei", "partner vor ort", "agentur"] },
    { href: "/de/mice-tuerkei", label: "MICE Türkei", icon: "\u{1F91D}", keywords: ["german", "mice", "kongress", "tagung", "incentive", "pco", "dmc"] },
    { href: "/de/eventproduktion-antalya", label: "Eventproduktion Antalya", icon: "\u{1F3D6}", keywords: ["german", "antalya", "belek", "kemer", "side", "resort", "kongresshotel"] },
    { href: "/de/traversen-mieten", label: "Traversen mieten", icon: "\u{1F9E9}", keywords: ["german", "traversen", "truss", "rigging", "portal"] },
    { href: "/de/konzertbuehne-mieten", label: "Konzertbühne mieten", icon: "\u{1F3B8}", keywords: ["german", "konzert", "festival", "buehne", "open air"] },
    { href: "/de/laufsteg-mieten", label: "Laufsteg mieten", icon: "\u{1F457}", keywords: ["german", "laufsteg", "runway", "modenschau", "catwalk"] },
    { href: "/de/tische-und-stuehle-mieten", label: "Tische & Stühle mieten", icon: "\u{1FA91}", keywords: ["german", "tische", "stuehle", "bankett", "mobiliar"] },
    { href: "/de/podium-preise", label: "Podium: Preise", icon: "\u{1F4B6}", keywords: ["german", "preis", "preise", "kosten", "podium", "kalkulation"] },
    { href: "/de/regionale-vermietung", label: "Regionale Vermietung", icon: "\u{1F5FA}", keywords: ["german", "staedte", "regional", "logistik", "istanbul", "ankara", "izmir"] },
    { href: "/de/arbeitsweise", label: "Arbeitsweise", icon: "\u{1F9ED}", keywords: ["german", "process", "ablauf", "arbeitsweise", "aufbau"] },
    { href: "/de/faq", label: "Häufige Fragen", icon: "\u{1F4A1}", keywords: ["german", "faq", "fragen", "antworten"] },
    { href: "/de/impressum", label: "Impressum", icon: "\u{1F4CB}", keywords: ["german", "impressum", "anbieterkennzeichnung", "firmierung", "handelsregister"] },
    { href: "/de/kontakt", label: "Kontakt", icon: "\u{260E}", keywords: ["german", "contact", "kontakt", "angebot", "telefon"] },
  ],
};

export const SEARCH_ROUTES = Object.values(SEARCH_ROUTE_GROUPS).flat();
