export const SEARCH_ROUTE_GROUPS = {
  tr: [
    { href: "/", label: "Anasayfa", icon: "\u{1F3E0}", keywords: ["home"] },
    { href: "/hizmetler", label: "Hizmetler", icon: "\u{1F9F0}", keywords: ["servis"] },
    { href: "/hakkimizda", label: "Hakkimizda", icon: "\u{1F465}", keywords: ["biz", "firma"] },
    { href: "/blog", label: "Blog", icon: "\u{1F4DD}", keywords: ["yazilar"] },
    { href: "/iletisim", label: "Iletisim", icon: "\u{260E}", keywords: ["telefon", "mail"] },
    { href: "/nasil-calisiyoruz", label: "Nasil Calisiyoruz", icon: "\u{1F9ED}", keywords: ["surec"] },
    { href: "/bolgesel-kiralama", label: "Bolgesel Kiralama", icon: "\u{1F5FA}", keywords: ["lojistik"] },
    { href: "/sss", label: "SSS", icon: "\u{1F4A1}", keywords: ["sik sorulan"] },
    { href: "/podyum-kiralama", label: "Podyum Kiralama", icon: "\u{1F451}", keywords: ["sahne"] },
    { href: "/led-ekran-kiralama", label: "LED Ekran Kiralama", icon: "\u{1F5A5}", keywords: ["video wall"] },
    { href: "/ses-isik-sistemleri", label: "Ses ve Isik Sistemleri", icon: "\u{1F3AD}", keywords: ["isik", "ses"] },
    { href: "/sahne-kiralama", label: "Sahne Kiralama", icon: "\u{1F3AA}", keywords: ["platform"] },
    { href: "/kurumsal-organizasyon", label: "Kurumsal Organizasyon", icon: "\u{1F3E2}", keywords: ["etkinlik"] },
    { href: "/truss-kiralama", label: "Truss Kiralama", icon: "\u{1F9E9}", keywords: ["konstruksiyon"] },
    { href: "/cadir-kiralama", label: "Cadir Kiralama", icon: "\u26FA", keywords: ["cadir"] },
    { href: "/masa-sandalye-kiralama", label: "Masa Sandalye Kiralama", icon: "\u{1FA91}", keywords: ["oturma"] },
  ],
  en: [
    { href: "/en", label: "Home", icon: "\u{1F3E0}", keywords: ["home"] },
    { href: "/en/about", label: "About Us", icon: "\u{1F465}", keywords: ["company", "about"] },
    { href: "/en/services", label: "Services", icon: "\u{1F9F0}", keywords: ["service"] },
    { href: "/en/blog", label: "Blog", icon: "\u{1F4DD}", keywords: ["articles"] },
    { href: "/en/contact", label: "Contact", icon: "\u{260E}", keywords: ["phone", "email"] },
    { href: "/en/how-we-work", label: "How We Work", icon: "\u{1F9ED}", keywords: ["process"] },
    { href: "/en/regional-rental", label: "Regional Rental", icon: "\u{1F5FA}", keywords: ["logistics"] },
    { href: "/en/faq", label: "FAQ", icon: "\u{1F4A1}", keywords: ["questions"] },
    { href: "/en/podium-rental", label: "Podium Rental", icon: "\u{1F451}", keywords: ["stage"] },
    { href: "/en/led-screen-rental", label: "LED Screen Rental", icon: "\u{1F5A5}", keywords: ["video wall"] },
    { href: "/en/sound-light-rental", label: "Sound and Light Systems", icon: "\u{1F3AD}", keywords: ["sound", "light"] },
    { href: "/en/stage-rental", label: "Stage Rental", icon: "\u{1F3AA}", keywords: ["platform"] },
    { href: "/en/corporate-events", label: "Corporate Events", icon: "\u{1F3E2}", keywords: ["event"] },
    { href: "/en/truss-rental", label: "Truss Rental", icon: "\u{1F9E9}", keywords: ["construction"] },
    { href: "/en/tent-rental", label: "Tent Rental", icon: "\u26FA", keywords: ["tent"] },
    { href: "/en/table-chair-rental", label: "Table and Chair Rental", icon: "\u{1FA91}", keywords: ["seating"] },
  ],
  ar: [
    { href: "/ar", label: "Arabic Home", icon: "\u{1F3E0}", keywords: ["arabic", "home"] },
    { href: "/ar/about", label: "Arabic About", icon: "\u{1F465}", keywords: ["arabic", "about"] },
    { href: "/ar/services", label: "Arabic Services", icon: "\u{1F9F0}", keywords: ["arabic", "services"] },
    { href: "/ar/projects", label: "Arabic Projects", icon: "\u{1F4BC}", keywords: ["arabic", "projects"] },
    { href: "/ar/contact", label: "Arabic Contact", icon: "\u{260E}", keywords: ["arabic", "contact"] },
  ],
};

export const SEARCH_ROUTES = Object.values(SEARCH_ROUTE_GROUPS).flat();
