export const SERVICE_DECISION_GUIDES = {
  ledScreen: {
    id: "led-ekran-soru-cevap",
    serviceName: "LED ekran",
    eyebrow: "LED ekran için soru-cevap rehberi",
    title: "LED ekran teknik terimlerini bilmeden doğru başlangıcı yapın",
    description: "Üç kısa cevapla ekranın ortamını, izleme mesafesini ve içerik akışını netleştirin. Sonuç, hangi panel ve teknik desteğin neden öne çıktığını anlatır.",
    learningNote: "Pixel pitch, ekrandaki LED noktaları arasındaki mesafedir. İzleyici ekrana yaklaştıkça daha küçük pitch; ekran uzaklaştıkça daha geniş pitch değerlendirilebilir.",
    plannerHref: "#hizmetler",
    plannerLabel: "LED ekran çözümlerini incele",
    terms: [
      ["pixel-pitch", "Pixel pitch"],
      ["nit-parlaklik", "Parlaklık (nit)"],
      ["kabinet", "Kabinet"],
      ["goruntu-islemcisi", "Görüntü işlemcisi"],
    ],
    checklist: ["Etkinlik tarihi, ilçe ve ekranın kurulacağı net alan", "Ekrana en yakın ve en uzak izleyicinin yaklaşık mesafesi", "Sunum, video, canlı kamera veya marka içeriği dosyaları"],
    questions: [
      {
        id: "environment",
        title: "Ekran nerede kullanılacak?",
        prompt: "İç ve dış mekânda panelin dayanımı ile parlaklık ihtiyacı farklıdır.",
        options: [
          {
            key: "indoor",
            label: "Kapalı salon / otel / fuar alanı",
            note: "Yakın izleme ve kontrollü ışık koşulları için.",
            answerTitle: "İç mekân paneli önceliklidir",
            answer: "Salon ışığı ve izleme mesafesine göre P2–P3 gibi daha sık piksel aralıklı iç mekân paneller değerlendirilir.",
          },
          {
            key: "outdoor",
            label: "Açık alan / gün ışığı",
            note: "Yağmur, toz ve gündüz görünürlüğü için.",
            answerTitle: "Dış mekân ve parlaklık planı gerekir",
            answer: "Hava koşullarına dayanıklı panel ve gündüz de okunabilir yüksek parlaklık birlikte planlanır; enerji ve sabitleme de kontrol edilir.",
          },
        ],
      },
      {
        id: "installation",
        title: "LED ekran nasıl konumlanacak?",
        prompt: "Ekranın yere mi kurulacağı, sahnede mi kullanılacağı yoksa truss'a mı asılacağı; ihtiyaç duyulan taşıyıcı sistemi değiştirir.",
        options: [
          {
            key: "floor",
            label: "Yerde veya podyum üzerinde",
            note: "Karşılama alanı, ürün noktası ya da alçak sahne kullanımı.",
            answerTitle: "Ekran ayağı ve zemin alanı planlanır",
            answer: "Ekranın kaplayacağı alan, seyircinin görüşü ve güvenli kablo geçişi birlikte kontrol edilir. Yükseklik gerekirse podyum çözümü de planlanır.",
            recommendations: [{ label: "Podyum kiralama", href: "/podyum-kiralama", why: "Ekranı veya ürünü görüş hattına güvenle yükseltmek için." }],
          },
          {
            key: "stage",
            label: "Sahnenin arkasında veya yanında",
            note: "Sunum, lansman ya da performans sahnesini destekleyecek.",
            answerTitle: "Ekran ve sahne aynı yerleşimde çözülür",
            answer: "LED ekran ölçüsü sahnenin enine, konuşmacı/performatör hareketine ve arka sıranın görüşüne göre birlikte belirlenir.",
            recommendations: [{ label: "Sahne kiralama", href: "/sahne-kiralama", why: "Ekran, konuşmacı alanı ve teknik geçişleri tek sahne planında toplamak için." }],
          },
          {
            key: "truss",
            label: "Truss'a asılı veya yüksek portal içinde",
            note: "Yüksek ekran, sahne portalı veya açık alan kurulumu.",
            answerTitle: "Ekran yükü ve rigging beraber değerlendirilir",
            answer: "Kabinet ağırlığı, asım noktaları, motor/ayak ihtiyacı ve emniyet elemanları; ekran ölçüsü netleşmeden varsayılmaz.",
            recommendations: [{ label: "Truss kiralama", href: "/truss-kiralama", why: "LED ekranın güvenli taşıyıcı sistemi ve rigging planı için." }],
          },
        ],
      },
      {
        id: "distance",
        title: "İzleyici ekrana ne kadar yaklaşacak?",
        prompt: "Bu soru, herkesin ekrandaki metni rahat okuyup okuyamayacağını belirler.",
        options: [
          {
            key: "close",
            label: "Yakın izleme: stant, toplantı veya küçük salon",
            note: "Metin ve detaylar ekrana yakından okunacak.",
            answerTitle: "Daha sık piksel aralığı düşünülür",
            answer: "Yakın izleyici için P2–P3 aralığı gibi daha ince görüntü detayını destekleyen panel seçenekleri öne çıkar.",
          },
          {
            key: "mid",
            label: "Orta mesafe: kurumsal salon veya lansman",
            note: "Sunum ve video, birkaç sıra geriden izlenecek.",
            answerTitle: "Dengeli çözünürlük ve alan seçilir",
            answer: "P3–P4 aralığı, ekran ölçüsü ve içerik türü birlikte değerlendirilerek okunabilirlik ile ekran alanı dengelenir.",
          },
          {
            key: "far",
            label: "Uzak izleme: açık alan veya geniş katılım",
            note: "Ekran uzaktaki seyirci için destekleyici olacak.",
            answerTitle: "Ekran alanı görüşü tamamlamalıdır",
            answer: "P4–P5 gibi seçenekler, ekranın net eni-boyu ve en uzak seyircinin görüşüyle birlikte ele alınır; yalnız pitch bilgisi yeterli değildir.",
          },
        ],
      },
      {
        id: "content",
        title: "Ekranda ağırlıkla ne gösterilecek?",
        prompt: "İçerik türü, ekranın yanında reji, kamera veya görüntü işlemcisi gerekip gerekmediğini gösterir.",
        options: [
          {
            key: "presentation",
            label: "Sunum, metin ve grafik",
            note: "Marka mesajı ve okunabilir içerik öncelikli.",
            answerTitle: "Okunabilirlik ve doğru en-boy oranı önemlidir",
            answer: "Sunum şablonu, logo ve metin büyüklüğü ekran ölçüsüyle kontrol edilir; böylece arka sıradaki katılımcı da içeriği takip eder.",
            recommendations: [{ label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Konuşmacı sesini, sahne ışığını ve ekranlı sunumu aynı akışta yönetmek için." }],
          },
          {
            key: "video",
            label: "Ürün filmi, geri sayım veya animasyon",
            note: "Görsel etki ve zamanlamalı içerik öncelikli.",
            answerTitle: "İçerik akışı ekrana göre hazırlanır",
            answer: "Video çözünürlüğü, oynatma sırası ve varsa ses senkronu kurulumdan önce test edilir.",
            recommendations: [{ label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Video sesini ve lansman anındaki ışık geçişlerini senkronlamak için." }],
          },
          {
            key: "live",
            label: "Canlı kamera / yayın",
            note: "Sahnedeki görüntü anlık ekrana taşınacak.",
            answerTitle: "Reji ve görüntü işleme katmanı eklenir",
            answer: "Kamera açıları, gecikme, görüntü işlemcisi ve operatör akışı LED kurulumuyla aynı teknik planda ele alınır.",
            recommendations: [{ label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Canlı programın sahne sesi ve teknik operasyonunu desteklemek için." }],
          },
        ],
      },
    ],
  },
  tent: {
    id: "cadir-soru-cevap",
    serviceName: "çadır",
    eyebrow: "Çadır için soru-cevap rehberi",
    title: "Çadır tipini ve alanını teknik bilgi gerektirmeden daraltın",
    description: "Etkinlik kullanımını, ölçeğini ve zemini seçin. Sonuçta pagoda mı, büyük açıklıklı sistem mi gerektiğini ve hangi saha kontrollerinin neden önemli olduğunu görün.",
    learningNote: "Çadır seçimi yalnız konuk sayısıyla yapılmaz. Masa düzeni, servis yolları, sahne/LED alanı, giriş-çıkış ve iklimlendirme için ayrılan boşluk da toplam alana eklenir.",
    plannerHref: "/cadir-hesaplama",
    plannerLabel: "Çadır alanını hesapla",
    terms: [
      ["ankraj", "Ankraj"],
      ["ruzgar-yuku", "Rüzgâr yükü"],
      ["su-tahliyesi", "Su tahliyesi"],
      ["teknik-kesif", "Teknik keşif"],
      ["cadir-zemini", "Çadır zemini"],
    ],
    checklist: ["Etkinlik tarihi, ilçe ve alanın ölçülü fotoğrafı", "Oturmalı/kokteyl düzeni ve tahmini konuk sayısı", "Sahne, LED ekran, iklimlendirme ve enerji ihtiyacı"],
    questions: [
      {
        id: "use",
        title: "Çadır alanını ne için kullanacaksınız?",
        prompt: "Kullanım türü, sadece çatının ölçüsünü değil içerideki boş alan ihtiyacını belirler.",
        options: [
          {
            key: "welcome",
            label: "Karşılama, kayıt, VIP veya küçük davet",
            note: "Kısa süreli ve bölümlenebilir kullanım.",
            answerTitle: "Pagoda tipi başlangıç noktasıdır",
            answer: "3×3, 4×4 ve 5×5 m pagoda modülleri; karşılama, kayıt veya küçük oturma alanlarını ihtiyaca göre yan yana kurmak için uygundur.",
          },
          {
            key: "dinner",
            label: "Yemekli davet / kurumsal buluşma",
            note: "Masa düzeni, servis koridoru ve konuk konforu önemli.",
            answerTitle: "Masa düzeniyle birlikte alan planı yapılır",
            answer: "Çadır eni-boyu masa yerleşimi, servis yolu ve sahne/ekran gereksinimiyle birlikte projelendirilir; yalnız sandalye sayısı yeterli ölçü vermez.",
          },
          {
            key: "large",
            label: "Fuar, festival veya geniş katılımlı etkinlik",
            note: "Kolonsuz büyük alan ve teknik altyapı ihtiyacı var.",
            answerTitle: "Büyük açıklıklı sistem değerlendirilir",
            answer: "10–40 m açıklık seçenekleri, ziyaretçi akışı ve sahne/stand alanına göre değerlendirilir; büyük alanda modül değil saha planı belirleyicidir.",
          },
        ],
      },
      {
        id: "scale",
        title: "Etkinlik alanı hangi ölçekte?",
        prompt: "Bu cevap, tek çadır mı yoksa birbirine bağlı modüller ya da büyük açıklık mı gerektiğini netleştirir.",
        options: [
          {
            key: "small",
            label: "Tek bölümlü küçük alan",
            note: "Kayıt, karşılama veya sınırlı konuk düzeni.",
            answerTitle: "Modüler pagoda yerleşimi yeterli olabilir",
            answer: "İhtiyaca göre 3×3, 4×4 veya 5×5 m modüller seçilir; giriş yönü ve yan kapamalar planlamaya dahil edilir.",
          },
          {
            key: "medium",
            label: "Birden çok kullanım alanı",
            note: "Yemek, servis, sahne veya ayrı VIP bölümü var.",
            answerTitle: "Alanları ayıran kurgu gerekir",
            answer: "Birden fazla modülün bağlantısı veya daha geniş bir sistem, akışın yağmurdan ve rüzgârdan etkilenmeden sürmesine yardımcı olur.",
          },
          {
            key: "large",
            label: "Geniş fuar / festival / belediye etkinliği",
            note: "Yüksek katılım, uzun süreli kullanım veya teknik prodüksiyon var.",
            answerTitle: "Açıklık ve kurulum takvimi öne çıkar",
            answer: "20, 30 ve 40 m açıklıklı çözümler; zemin, lojistik, enerji ve güvenlik keşfiyle birlikte planlanır. Büyük projelerde briefin en az 7–10 gün önce paylaşılması önerilir.",
          },
        ],
      },
      {
        id: "ground",
        title: "Çadır zemine nasıl sabitlenecek?",
        prompt: "Toprak, sert yüzey veya mevcut bir raylı/yapısal zemin; sabitleme biçimini ve saha hazırlığını doğrudan etkiler.",
        options: [
          {
            key: "soil",
            label: "Çim, toprak veya açık saha",
            note: "Zemin ankrajı, kot farkı ve su tahliyesi kontrol edilmeli.",
            answerTitle: "Ankraj ve su tahliyesi değerlendirilir",
            answer: "Zemin eğimi, rüzgâr yönü ve yağışta suyun uzaklaştırılması saha keşfinde kontrol edilir; sabitleme buna göre belirlenir.",
          },
          {
            key: "hard",
            label: "Beton, asfalt veya hassas kaplama",
            note: "Yüzeye zarar vermeyen sabitleme planı önemli.",
            answerTitle: "Yüzeye uygun sabitleme gerekir",
            answer: "Mevcut zemin, yüzey hassasiyeti ve yük dağılımı görülmeden sabitleme yöntemi kesinleştirilmez.",
          },
          {
            key: "rail",
            label: "Mevcut raylı, platformlu veya yapısal zemin",
            note: "Bağlantı noktaları ve mevcut yapının taşıma koşulları teyit edilmeli.",
            answerTitle: "Mevcut yapı üzerinde keşif gerekir",
            answer: "Ray, platform veya mevcut taşıyıcıya bağlantıda yapının ölçüsü, bağlantı noktaları ve yük aktarımı teknik ekip tarafından yerinde değerlendirilir.",
          },
          {
            key: "unknown",
            label: "Zemini henüz bilmiyorum",
            note: "Mekân net değil veya alanı görmedim.",
            answerTitle: "Fotoğraf ve ölçüyle keşif başlatılır",
            answer: "Alan fotoğrafı, yaklaşık ölçü ve mekân konumu ilk teknik değerlendirme için yeterli başlangıcı sağlar; final plan sahada yapılır.",
          },
        ],
      },
      {
        id: "floor",
        title: "Çadırın içinde zemini nasıl kullanmak istiyorsunuz?",
        prompt: "Düzeltme, yükseltme ve yüzey kaplama ihtiyaçları; çadır kurulduktan sonra değil, ölçü alınırken belirlenmelidir.",
        options: [
          {
            key: "level",
            label: "Zemin eğimli; düzeltme veya yükseltme gerekebilir",
            note: "Masa düzeni, sahne veya ürün alanı için düz yüzey gerekli.",
            answerTitle: "Podyumla zemin düzeltme planlanır",
            answer: "Kot farkı, masa ayakları ve güvenli geçişler ölçülür; gerektiğinde geçici podyum zeminle alan dengelenir.",
            recommendations: [{ label: "Podyum kiralama", href: "/podyum-kiralama", why: "Çadır içindeki eğimli alanı düz ve kullanılabilir bir zemine çevirmek için." }],
          },
          {
            key: "carpet",
            label: "Zemin düz; halı veya şık bir yüzey istiyorum",
            note: "Konuk konforu, marka görünümü veya koruyucu yüzey için.",
            answerTitle: "Kaplama ihtiyacı çadırla birlikte planlanır",
            answer: "Halı rengi, yürüyüş yolları, kenar bitişleri ve varsa marka uygulaması çadır yerleşimiyle birlikte netleştirilir.",
            recommendations: [{ label: "Çadır kurulum detayları", href: "/cadir-kiralama", why: "Halı, zemin kaplaması ve giriş yollarını çadır yerleşimine göre planlamak için." }],
          },
          {
            key: "direct",
            label: "Mevcut zemin doğrudan kullanılabilir",
            note: "Yükseltme ya da özel kaplama ihtiyacı görünmüyor.",
            answerTitle: "Yine de geçiş ve yağmur senaryosu kontrol edilir",
            answer: "Masa, kablo, servis ve giriş yollarında takılma riski yaratmayan akış; keşif sırasında mevcut yüzey üzerinden teyit edilir.",
          },
        ],
      },
      {
        id: "inside",
        title: "Çadırın içinde başka hangi etkinlik kurgusu olacak?",
        prompt: "Bu cevap, çadırı yalnız bir örtü değil; bütün etkinliğin teknik merkezi olarak planlamamızı sağlar.",
        options: [
          {
            key: "seating",
            label: "Oturma düzeni, yemek veya karşılama",
            note: "Masa, sandalye, servis ve konuk dolaşımı öncelikli.",
            answerTitle: "Mobilya ve servis yolları alan hesabına girer",
            answer: "Masa-sandalye yerleşimi, servis koridoru ve girişler çadırın net iç ölçüsüyle birlikte çizilir; konuk sayısı tek başına yeterli değildir.",
            recommendations: [{ label: "Masa ve sandalye kiralama", href: "/masa-sandalye-kiralama", why: "Oturma düzeni ve servis akışını çadır alanına göre tamamlamak için." }],
          },
          {
            key: "stage",
            label: "Konuşma, ödül veya performans sahnesi",
            note: "Sahne, mikrofon ve ışıkla bir program akışı olacak.",
            answerTitle: "Sahne ve teknik ekip çadır planına bağlanır",
            answer: "Sahne ölçüsü, seyir yönü, kablo geçişleri ve teknik ekip alanı çadır kurulmadan önce ayrılır; sonradan eklemek akışı daraltabilir.",
            recommendations: [
              { label: "Sahne kiralama", href: "/sahne-kiralama", why: "Konuşma veya performans alanını çadırın net ölçüsüne göre kurmak için." },
              { label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Mikrofon, sahne ışığı ve program akışını teknik olarak desteklemek için." },
            ],
          },
          {
            key: "launch",
            label: "Lansman, LED ekran veya marka gösterimi",
            note: "Ürün, video veya güçlü görsel mesaj öncelikli.",
            answerTitle: "Görsel kurgu ve teknik altyapı ayrılır",
            answer: "LED ekranın görüş yönü, ürün alanı, sahne yüksekliği ve enerji-kablo güzergâhı çadır yerleşimiyle birlikte çözülür.",
            recommendations: [
              { label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Sunum, ürün filmi ve marka içeriğini görünür kılmak için." },
              { label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Lansman anındaki ses ve ışık geçişlerini yönetmek için." },
            ],
          },
        ],
      },
    ],
  },
  soundLight: {
    id: "ses-isik-soru-cevap",
    serviceName: "ses ve ışık sistemi",
    eyebrow: "Ses ve ışık için soru-cevap rehberi",
    title: "“Kaç watt gerekir?” sorusundan doğru teknik plana geçin",
    description: "Etkinlik akışını, konuk ölçeğini ve mekânı seçin. Sonuç, ses kapsamı, ışık kurgusu ve teknik ekibin neden gerektiğini sade biçimde anlatır.",
    learningNote: "Ses sistemi yalnız hoparlör gücü değildir; konuşmanın anlaşılır olması, müziğin dengesi ve en uzak izleyicinin kapsaması birlikte değerlendirilir. Işıkta da sahne, salon ve kamera ihtiyaçları ayrıdır.",
    plannerHref: "/etkinlik-planlayici",
    plannerLabel: "Etkinliğin tamamını planla",
    terms: [
      ["line-array", "Line array"],
      ["foh", "FOH"],
      ["delay-hoparlor", "Delay hoparlör"],
      ["dmx", "DMX"],
    ],
    checklist: ["Etkinlik akışı ve konuşmacı/sanatçı listesi", "Mekân planı ile en uzak izleyicinin konumu", "Mikrofon, playback, canlı müzik ve kamera ihtiyacı"],
    questions: [
      {
        id: "flow",
        title: "Etkinlikte ses ve ışık en çok ne için kullanılacak?",
        prompt: "Konuşma, canlı performans ve lansman aynı ekipmanı farklı şekilde kullanır.",
        options: [
          {
            key: "speech",
            label: "Konuşma, panel veya konferans",
            note: "Mikrofon netliği ve sunum görünürlüğü öncelikli.",
            answerTitle: "Konuşma anlaşılırlığı öne çıkar",
            answer: "Kablosuz/kablolu mikrofon sayısı, sahne monitörü ve salon kapsaması konuşmacıların sesini her sırada net tutacak şekilde planlanır.",
            recommendations: [
              { label: "Sahne kiralama", href: "/sahne-kiralama", why: "Konuşmacı alanı ve seyirci görüşünü netleştirmek için." },
              { label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Sunum içeriğini arka sıradaki katılımcıya da ulaştırmak için." },
            ],
          },
          {
            key: "launch",
            label: "Lansman, ödül veya marka gösterisi",
            note: "Müzik geçişi, video ve sahne atmosferi öncelikli.",
            answerTitle: "Zamanlama ve sahne etkisi birlikte kurulur",
            answer: "Playback, LED ekran içeriği, ışık geçişleri ve anonslar tek akışta prova edilir; böylece açılış anı teknik olarak bölünmez.",
            recommendations: [
              { label: "Sahne kiralama", href: "/sahne-kiralama", why: "Lansman anını ve konuşmacı hareketini tek sahne düzeninde toplamak için." },
              { label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Geri sayım, ürün filmi ve marka içeriğini görünür kılmak için." },
            ],
          },
          {
            key: "concert",
            label: "Canlı müzik / performans",
            note: "Sahne monitörü, miksaj ve geniş kapsama öncelikli.",
            answerTitle: "Miksaj ve sahne altyapısı büyür",
            answer: "FOH miksaj, monitör sistemi, enstrüman girişleri ve gerekirse line array kapsaması sanatçı teknik ihtiyaçlarıyla birlikte ele alınır.",
            recommendations: [
              { label: "Sahne kiralama", href: "/sahne-kiralama", why: "Performans alanı, monitörler ve sahne trafiği için." },
              { label: "Truss kiralama", href: "/truss-kiralama", why: "Işık ve teknik ekipmanın güvenli taşıyıcı sistemi için." },
            ],
          },
        ],
      },
      {
        id: "audience",
        title: "Kaç kişiye ulaşmanız gerekiyor?",
        prompt: "Konuk sayısı, sistemin yalnız gücünü değil hoparlörlerin nereye yerleşeceğini de etkiler.",
        options: [
          {
            key: "small",
            label: "1–100 kişi",
            note: "Yakın mesafeli salon veya küçük etkinlik.",
            answerTitle: "Kompakt ve kontrollü kapsama planlanır",
            answer: "Sistemin sesi gereğinden fazla açılmadan, konuşma ve arka plan müziğinin dengeli duyulacağı bir yerleşim hedeflenir.",
          },
          {
            key: "medium",
            label: "101–500 kişi",
            note: "Salonun arka sıraları ve sahne enerjisi önemli.",
            answerTitle: "Ön ve arka kapsama birlikte ölçülür",
            answer: "Ana hoparlör yerleşimi, mikrofon sayısı ve ışık noktaları oturma düzeniyle birlikte belirlenir; sesin ilk ve son sırada dengeli olması hedeflenir.",
          },
          {
            key: "large",
            label: "500+ kişi veya geniş açık alan",
            note: "Uzak izleyici ve alanın bölümleri ayrı düşünülmeli.",
            answerTitle: "Bölgesel kapsama ve delay planı gerekir",
            answer: "Büyük alanlarda ana sistemin yanında gecikmeli hoparlör noktaları, kablo güzergâhı ve teknik ekip büyüklüğü proje planına girer.",
          },
        ],
      },
      {
        id: "venue",
        title: "Mekân hangi koşullarda?",
        prompt: "Aynı ekipman kapalı salonda ve açık alanda aynı sonuç vermez.",
        options: [
          {
            key: "indoor",
            label: "Kapalı salon / otel",
            note: "Tavan, yankı ve elektrik noktaları kontrol edilir.",
            answerTitle: "Akustik ve görüş engelleri kontrol edilir",
            answer: "Hoparlör ve ışık yerleşimi, salonun yankısı, tavan yüksekliği ve konukların görüş hattıyla birlikte değerlendirilir.",
          },
          {
            key: "outdoor",
            label: "Açık alan",
            note: "Rüzgâr, mesafe ve hava koruması önemli.",
            answerTitle: "Kapsama, hava ve enerji planı eklenir",
            answer: "Açık alanda sesin yayılımı, rüzgâr, güvenli kablo geçişleri ve gerekirse hava koşullarına karşı koruma aynı keşifte netleştirilir.",
          },
          {
            key: "hybrid",
            label: "Çadır veya yarı açık alan",
            note: "Yapı, ses yansıması ve iklim koşulu birlikte etkili.",
            answerTitle: "Yapının akustiği ayrıca değerlendirilir",
            answer: "Çadırın ölçüsü, kapalı yüzeyleri ve konuk düzeni ses dağılımını değiştirir; sistem bu fiziksel koşullara göre ayarlanır.",
          },
        ],
      },
    ],
  },
  truss: {
    id: "truss-soru-cevap",
    serviceName: "truss",
    eyebrow: "Truss için soru-cevap rehberi",
    title: "“Kaç metre truss?” demeden önce güvenli kurguyu belirleyin",
    description: "Truss yalnızca dekoratif bir çerçeve değildir. Kullanım amacını, formu ve taşınacak ekipmanı seçerek hangi teknik verinin neden gerekli olduğunu görün.",
    learningNote: "Truss teklifinde metre tek başına güvenli bilgi değildir. Form, yükün nerede asılacağı, yükseklik, ayak/motor ihtiyacı ve mekânın taşıma koşulları birlikte değerlendirilir.",
    plannerHref: "/etkinlik-planlayici",
    plannerLabel: "Etkinliğin tamamını planla",
    terms: [
      ["truss", "Truss"],
      ["rigging", "Rigging"],
      ["swl", "SWL"],
      ["zincirli-vinc", "Zincirli vinç"],
    ],
    checklist: ["Mekânın en-boy-yükseklik ölçüsü veya planı", "Asılacak LED, ışık, ses ya da marka elemanlarının listesi", "Kurulum alanı, zemin durumu ve yükleme saati"],
    questions: [
      {
        id: "use",
        title: "Truss sistemi neyi taşıyacak veya çerçeveleyecek?",
        prompt: "Kullanım amacı, seçilecek formu ve güvenlik hesabını doğrudan değiştirir.",
        options: [
          {
            key: "backdrop",
            label: "Sahne arka fonu / marka çerçevesi",
            note: "Hafif görsel yüzey veya dekor için.",
            answerTitle: "Düz veya U form başlangıç noktası olabilir",
            answer: "Marka alanının eni-boyu ve sergilenecek yüzeyin ağırlığına göre düz hat, U form ya da portal düzeni değerlendirilir.",
            recommendations: [{ label: "Sahne kiralama", href: "/sahne-kiralama", why: "Marka fonu ve truss düzenini sahne ölçüsüyle uyumlu kurmak için." }],
          },
          {
            key: "lighting",
            label: "Işık ve sahne ekipmanı",
            note: "Projektör, hareketli başlık veya dekor asılacak.",
            answerTitle: "Yük dağılımı teknik planın parçasıdır",
            answer: "Her ekipmanın ağırlığı ve asılacağı nokta listelenir; trussun formu, ayakları veya motorları bu yük planına göre belirlenir.",
            recommendations: [{ label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Asılacak ışık ve sahne ekipmanını doğru teknik listeyle planlamak için." }],
          },
          {
            key: "led",
            label: "LED ekran / büyük görsel sistem",
            note: "Ekran asımı veya yüksek sahne portalı gerekli.",
            answerTitle: "Rigging ve ekran yükü birlikte hesaplanır",
            answer: "LED ekranın ölçüsü, kabinet ağırlığı, asım noktaları ve yedek güvenlik elemanları truss düzeninden ayrı düşünülemez.",
            recommendations: [{ label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Ekran ölçüsü, kabinet yükü ve görüntü altyapısını netleştirmek için." }],
          },
        ],
      },
      {
        id: "form",
        title: "Alanın hangi kısmını kapsaması gerekiyor?",
        prompt: "Truss formu, sadece estetik değil; kullanılabilir sahne alanı ve ekipmanın konumunu da belirler.",
        options: [
          {
            key: "line",
            label: "Tek düz hat / arka fon",
            note: "Küçük sahne veya tek yönlü marka alanı.",
            answerTitle: "Net en-boy ölçüsüyle düz hat planlanır",
            answer: "Truss uzunluğu, afiş/ekran eni ve güvenli yan açıklıklar birlikte ölçülür; geçiş alanları ayrıca korunur.",
          },
          {
            key: "portal",
            label: "U veya kare sahne portalı",
            note: "Işık, ekran ve sahneyi tek çerçevede toplamak için.",
            answerTitle: "Yükseklik ile ayak konumları birlikte seçilir",
            answer: "Portal genişliği, tavan veya açık alan yüksekliği, ayakların zemindeki yeri ve seyirci geçişi aynı planda netleşir.",
          },
          {
            key: "custom",
            label: "Kemer, daire veya özel form",
            note: "Mimari görünüm veya özel sahne tasarımı için.",
            answerTitle: "Özel kurgu teknik çizimle değerlendirilir",
            answer: "Formun taşıyacağı ekipman, bağlantı noktaları ve kurulum alanı proje bazında çizilir; yalnız görsel referansla karar verilmez.",
          },
        ],
      },
      {
        id: "load",
        title: "Asılacak ekipmanın kapsamı nedir?",
        prompt: "Bu soru güvenlik açısından kritiktir; kesin taşıma kapasitesi saha ve ekipman verisi olmadan varsayılmaz.",
        options: [
          {
            key: "light",
            label: "Hafif marka elemanı / dekor",
            note: "Küçük tabela, kumaş veya sınırlı ışık.",
            answerTitle: "Yine de bağlantı noktaları teyit edilir",
            answer: "Hafif ekipmanda bile ölçü, rüzgâr ve bağlantı biçimi kontrol edilir; güvenlik ekipmanı proje kapsamına göre belirlenir.",
          },
          {
            key: "technical",
            label: "Işık, ses veya orta ölçekli LED",
            note: "Birden fazla teknik ekipman asılacak.",
            answerTitle: "Ekipman listesi ve dağılım gerekir",
            answer: "Her cihazın adet ve ağırlığı, truss üzerindeki konumu ve gerektiğinde motor/ayak düzeni tekliften önce netleştirilir.",
          },
          {
            key: "heavy",
            label: "Büyük LED veya hareketli sistem",
            note: "Yüksek ağırlık ve dinamik kullanım ihtimali var.",
            answerTitle: "Rigging keşfi ve güvenlik planı zorunludur",
            answer: "Büyük yükte statik plan, uygun asım noktaları, motor sistemi ve güvenlik yedekleri teknik ekip tarafından ayrıca değerlendirilir.",
          },
        ],
      },
    ],
  },
  stage: {
    id: "sahne-soru-cevap",
    serviceName: "sahne",
    eyebrow: "Sahne için soru-cevap rehberi",
    title: "Sahne ölçüsünü ve yüksekliğini üç cevapla daraltın",
    description: "Etkinlik akışını, sahne ölçeğini ve mekân koşulunu seçin. Sonuçta başlangıç m²/yükseklik aralığını ve hangi ek tekniklerin devreye girdiğini görün.",
    learningNote: "Sahne alanı yalnız sahnedeki kişi sayısı değildir. Sanatçı/konuşmacı hareketi, enstrüman, LED ekran, truss ayakları, merdiven-rampa ve güvenli yan boşluklar birlikte hesaplanır.",
    plannerHref: "/etkinlik-planlayici",
    plannerLabel: "Etkinliğin tamamını planla",
    terms: [
      ["sahne-yuku", "Sahne yükü"],
      ["gorus-hatti", "Görüş hattı"],
      ["riser", "Riser"],
      ["korkuluk-merdiven", "Korkuluk ve merdiven"],
    ],
    checklist: ["Etkinlik akışı, sahne üstü kişi sayısı ve ekipman listesi", "Mekân planı ile en uzak seyircinin görüş mesafesi", "LED ekran, truss, ses-ışık ve rampa/merdiven ihtiyacı"],
    questions: [
      {
        id: "event",
        title: "Sahnede nasıl bir akış olacak?",
        prompt: "Konuşma, lansman ve konser aynı sahne alanını kullanmaz.",
        options: [
          {
            key: "speech",
            label: "Konuşma / konferans / panel",
            note: "Kürsü, konuşmacı ve sunum görünürlüğü öncelikli.",
            answerTitle: "Konuşmacı alanı ve görüş hattı öne çıkar",
            answer: "Kürsü, panelist oturumu ve ekranın birbirini kapatmaması; sahne alanı kadar seyircinin görüşü de planlanır.",
            recommendations: [
              { label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Mikrofon netliğini ve konuşmacı ışığını sağlamak için." },
              { label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Sunum ve içerikleri arka sıralara taşımak için." },
            ],
          },
          {
            key: "launch",
            label: "Lansman / ödül / tören",
            note: "Ürün, marka anı ve protokol geçişi önemli.",
            answerTitle: "Sahne üzeri hareket alanı artırılır",
            answer: "Ürün konumu, ödül geçişi, fotoğraf alanı ve LED içerik akışı aynı sahne yerleşiminde düşünülür.",
            recommendations: [
              { label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Ürün filmi, geri sayım ve marka içeriği için." },
              { label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "Anons, müzik ve ışık geçişlerini yönetmek için." },
            ],
          },
          {
            key: "concert",
            label: "Konser / performans / festival",
            note: "Sanatçı, enstrüman ve yoğun teknik kullanım var.",
            answerTitle: "Geniş ve güçlendirilmiş sahne kurgusu gerekir",
            answer: "Sahne üstü yük, monitörler, backline, truss/LED ve sahne trafiği birbirinden bağımsız planlanmaz.",
            recommendations: [
              { label: "Ses ve ışık sistemleri", href: "/ses-isik-sistemleri", why: "FOH miksaj, sahne monitörü ve performans ışığı için." },
              { label: "Truss kiralama", href: "/truss-kiralama", why: "Işık, LED ve rigging altyapısını güvenle taşımak için." },
              { label: "LED ekran kiralama", href: "/led-ekran-kiralama", why: "Uzak seyircinin sahneyi ve içerikleri takip etmesi için." },
            ],
          },
        ],
      },
      {
        id: "scale",
        title: "Sahne hangi ölçekte olmalı?",
        prompt: "Başlangıç paketi seçilirken sahne üstü akış ve seyirci kapasitesi birlikte değerlendirilir.",
        options: [
          {
            key: "small",
            label: "Küçük kurumsal akış",
            note: "16 m² · 4 × 4 m · 40 cm başlangıç paketi.",
            answerTitle: "16 m² / 4 × 4 m başlangıç noktasıdır",
            answer: "Kısa konuşma, küçük panel ve kontrollü sunum akışında 40 cm yükseklikle başlayıp mekân görüşüne göre netleştirmek uygundur.",
          },
          {
            key: "medium",
            label: "Orta ölçekli lansman veya tören",
            note: "24 m² · 6 × 4 m · 60 cm başlangıç paketi.",
            answerTitle: "24 m² / 6 × 4 m daha rahat akış sağlar",
            answer: "Birden fazla konuşmacı, ödül geçişi veya ürün anı için 60 cm yüksekliğe sahip orta sahne başlangıç çözümüdür.",
          },
          {
            key: "large",
            label: "Konser, festival veya geniş sahne",
            note: "48 m² · 8 × 6 m · 80–100 cm başlangıç paketi.",
            answerTitle: "48 m² / 8 × 6 m ve üzeri değerlendirilir",
            answer: "Yüksek katılım ve teknik yoğunlukta 80–100 cm yükseklik, rampa-korkuluk ve truss/LED altyapısıyla birlikte ele alınır.",
          },
        ],
      },
      {
        id: "venue",
        title: "Sahne hangi mekânda kurulacak?",
        prompt: "Mekân tipi; zemin, yükseklik, hava koşulu ve ek teknik altyapıyı değiştirir.",
        options: [
          {
            key: "indoor",
            label: "Kapalı salon / otel",
            note: "Tavan yüksekliği ve yükleme koşulları kontrol edilecek.",
            answerTitle: "Tavan ve salon görüşü kontrol edilir",
            answer: "Truss, ışık ve LED ekran varsa tavan yüksekliği; konuk düzeni varsa en uzak görüş noktası keşifte değerlendirilir.",
          },
          {
            key: "outdoor",
            label: "Açık alan",
            note: "Zemin, rüzgâr ve hava koruması önemli.",
            answerTitle: "Zemin ve hava senaryosu eklenir",
            answer: "Açık alanda stabilite, sabitleme, güvenli kablo geçişi ve yağmur/rüzgâr planı sahne tasarımının parçasıdır.",
          },
          {
            key: "tent",
            label: "Çadır veya geçici yapı",
            note: "İç yükseklik ve yapının teknik sınırları önemli.",
            answerTitle: "Çadır yapısı ile teknik kurgu birlikte okunur",
            answer: "Çadırın açıklığı, iç yüksekliği, zemin ve olası asım noktaları görülmeden truss/LED/ışık yerleşimi kesinleştirilmez.",
          },
        ],
      },
    ],
  },
};
